// Generated by CoffeeScript 1.4.0
(function() {
  var AppRouter, Customer, CustomerCollection, CustomerListView, CustomerView, app, customer;

  AppRouter = Backbone.Router.extend({
    routes: {
      '': 'home',
      'customers': 'listCustomers'
    },
    listCustomers: function() {
      var customerList;
      customerList = new CustomerCollection;
      return customerList.fetch({
        success: function() {
          return $('#content').html(new CustomerListView({
            model: customerList
          }).el);
        }
      });
    }
  });

  Customer = Backbone.Model.extend({
    idAttribute: 'uid',
    urlRoot: '/customers'
  });

  customer = new Customer;

  CustomerCollection = Backbone.Collection.extend({
    model: Customer,
    url: '/customers'
  });

  CustomerListView = Backbone.View.extend({
    initialize: function() {
      return this.render();
    },
    render: function() {
      var customers, len, _i, _len, _results;
      customers = this.model.models;
      len = customers.length;
      $(this.el).html("<ul class='customers'></ul>");
      _results = [];
      for (_i = 0, _len = customers.length; _i < _len; _i++) {
        customer = customers[_i];
        console.log(new CustomerView({
          model: customer
        }).render().el);
        _results.push($('.customers', this.el).append(new CustomerView({
          model: customer
        }).render().el));
      }
      return _results;
    }
  });

  CustomerView = Backbone.View.extend({
    tagName: 'li',
    initialize: function() {
      this.model.bind('change', this.render, this);
      return this.model.bind('destroy', this.close, this);
    },
    render: function() {
      console.log(this.model.toJSON());
      $(this.el).html(this.model.toJSON().uid);
      return this;
    }
  });

  /* Start the app
  */


  app = new AppRouter;

  Backbone.history.start();

}).call(this);
